### ISSUE TITLE
FR: reduce strictness or return as much as you can

### ISSUE THREAD

**Issue by XSven** [haukex/Config-Perl#3]
From the perspective of its scope `Config::Perl` is exactly what I need. Unfortunately it follows an all (`parse_or_die()`) or nothing (`parse_or_undef()`) implementation strategy. What I need is something like `parse_or_warn()`: an object method that returns as much as it can parse and raises a verbose or non-verbose warning about the things that it cannot parse. The verbosity of the warning could depend on the `$DEBUG` level.

**Comment by haukex** [comment]
Thanks for the suggestion. It's been quite a while since I last worked on this module, but from a quick look at the code, I suspect the issue with implementing something like that will be that in several places I rely on the exception interrupting the code flow. In other words, I suspect it would be the roughly the same amount of work to implement a warning as simply supporting the feature currently not supported (i.e. nontrivial).

Could you clarify your use case? Could you show an example of the Perl code you're trying to parse, what are the errors you're getting, and what kind of output would you expect instead?

**Comment by XSven** [comment]
My use case refers to legacy(!) `.pl` files that we `require()` from other perl source code. At the file-scope level the lecacy `.pl` contains 2 optional variable definitions. Furthermore the legacy `.pl` contains 3 subroutine definitions that implement an interface. One of them simply sets a hash variable. The other two may contain any kind of perl source code but do not define any variables. Non of the variable definitions is prefixed by `my`, `our`, `state`, etc. Non of the variable names is fully qualified. The legay `.pl` contains no package declaration. This is an example 

```
$encoding='ISO-8859-1';
$separator="\t";

sub setLevels {
  $Foo{A} = 0;
  $Foo{B} = 1;
  $Foo{C} = 2;
}
...
```

I have omitted the two subroutines that may contain any kind of perl source code. Please do not invest any time in a non-generic amendment of `Config::Perl`. Saying that I think even the wish that `Config::Perl` could detect and return leaky variable definitions inside a subroutine like `setLevels()` sounds to me like an improper amendment.

**Comment by XSven** [comment]
Sideremark: The legacy `.pl` files should have never been used as configuration files. Perl configurations should be restricted to something that looks like [Config::Any::Perl#EXAMPLE](https://metacpan.org/pod/Config::Any::Perl#DESCRIPTION). I have parsed this example using `Config::Perl` . I dislike the output

```
  {
    '_' => [
      {
        'name' => 'TestApp',
        'Model::Baz' => {
          'qux' => 'xyzzy'
        },
        'Controller::Foo' => {
          'foo' => 'bar'
        }
      }
    ]
  }
```
because it contains two additional layers of indirection ( `{ [ ... ] }` ).

**Comment by haukex** [comment]
How about using [PPI](https://metacpan.org/pod/PPI) to munge the file before passing to Config::Perl?

```perl
use warnings;
use strict;
use PPI;
use Config::Perl;
use Data::Dumper;

my $INPUT = <<'EOF';
$encoding='ISO-8859-1';
$separator="\t";
sub setLevels {
	$Foo{A} = 0;
	$Foo{B} = 1;
	$Foo{C} = 2;
}
sub somethingElse {
	say "Hello, World!";
}
EOF

my $doc = PPI::Document->new(\$INPUT) or die PPI::Document->errstr;
my $found = $doc->find('PPI::Statement::Sub') or die "no subs found";

for my $sub (@$found) {
	$doc->remove_child($sub) or die "remove failed";
	next unless $sub->name eq 'setLevels';
	for my $ch ($sub->block->children) {
		$sub->block->remove_child($ch) or die "remove failed";
		$doc->add_element($ch) or die "add failed";
	}
}
print $doc->content;

my $conf = Config::Perl->new->parse_or_die(\$doc->content);

print Dumper($conf);

__END__
$encoding='ISO-8859-1';
$separator="\t";

        $Foo{A} = 0;
        $Foo{B} = 1;
        $Foo{C} = 2;

$VAR1 = {
          '$separator' => '     ',
          '$encoding' => 'ISO-8859-1',
          '%Foo' => {
                      'A' => 0,
                      'B' => 1,
                      'C' => 2
                    }
        };
```

**Comment by XSven** [comment]
Thanks for the suggestion. I will not follow that perl configuration approach anymore.
